/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.view;

import javax.swing.JMenuItem;

/**
 *
 * @author marko
 */
public class ViewMain extends javax.swing.JFrame {

    /**
     * Creates new form ViewMain
     */
    public ViewMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuServer = new javax.swing.JMenu();
        jMenuItemStart = new javax.swing.JMenuItem();
        jMenuItemStop = new javax.swing.JMenuItem();
        jMenuConfiguration = new javax.swing.JMenu();
        jMenuItemDatabase = new javax.swing.JMenuItem();
        jMenuItemCommunication = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuServer.setText("Server");

        jMenuItemStart.setText("Start");
        jMenuServer.add(jMenuItemStart);

        jMenuItemStop.setText("Stop");
        jMenuServer.add(jMenuItemStop);

        jMenuBar1.add(jMenuServer);

        jMenuConfiguration.setText("Configuration");

        jMenuItemDatabase.setText("Database");
        jMenuConfiguration.add(jMenuItemDatabase);

        jMenuItemCommunication.setText("Communication");
        jMenuConfiguration.add(jMenuItemCommunication);

        jMenuBar1.add(jMenuConfiguration);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuConfiguration;
    private javax.swing.JMenuItem jMenuItemCommunication;
    private javax.swing.JMenuItem jMenuItemDatabase;
    private javax.swing.JMenuItem jMenuItemStart;
    private javax.swing.JMenuItem jMenuItemStop;
    private javax.swing.JMenu jMenuServer;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JMenuItem getjMenuItemStart() {
        return jMenuItemStart;
    }

    public JMenuItem getjMenuItemDatabase() {
        return jMenuItemDatabase;
    }

    public javax.swing.JMenuItem getjMenuItemStop() {
        return jMenuItemStop;
    }

    public JMenuItem getjMenuItemCommunication() {
        return jMenuItemCommunication;
    }

}
